openapi: 3.0.0
info:
  title: Authentication API
  version: 0.0.1
  description: API для регистрации, входа и подтверждения учетных записей пользователей.

servers:
  - url: http://localhost:5000/api
    description: Local server

paths:
  /auth/confirm:
    get:
      tags:
        - Auth
      summary: Подтверждение пользователя
      description: Подтверждает учетную запись пользователя на основе идентификатора.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Уникальный идентификатор пользователя.
      responses:
        '200':
          description: Успешное подтверждение
          content:
            application/json:
              schema:
                type: string
                example: "Confirmation successful"
        '400':
          description: Ошибка подтверждения
          content:
            application/json:
              schema:
                type: string
                example: "Failed to find a user with this id"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"

  /auth/signup:
    post:
      tags:
        - Auth
      summary: Регистрация нового пользователя
      description: Регистрирует нового пользователя на основе email и пароля.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Электронная почта пользователя.
                password:
                  type: string
                  format: password
                  description: Пароль пользователя.
              required:
                - email
                - password
      responses:
        '200':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Уникальный идентификатор пользователя
                  email:
                    type: string
                    format: email
                    description: Электронная почта пользователя
                  activated:
                    type: integer
                    description: Статус подтверждения пользователя (0 — не активирован, 1 — активирован)
                    example: 0
        '400':
          description: Ошибка при регистрации
          content:
            application/json:
              schema:
                type: string
              examples:
                InvalidInput:
                  summary: Неверные данные
                  value: "Invalid input"
                EmailReserved:
                  summary: Электронная почта уже используется
                  value: "This email already had been reserved"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
  /auth/signin:
    post:
      tags:
        - Auth
      summary: Аутентификация пользователя
      description: Аутентифицирует пользователя на основе email и пароля.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Электронная почта пользователя
                password:
                  type: string
                  format: password
                  description: Пароль пользователя
              required:
                - email
                - password
      responses:
        '200':
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                type: string
                example: "Authentication successful"
        '400':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                type: string
              examples:
                InvalidInput:
                  summary: Неверные данные
                  value: "Invalid input"
                UserNotFound:
                  summary: Пользователь не найден
                  value: "Failed to find this user"
                UserNotActivated:
                  summary: Пользователь не активирован
                  value: "This user is not activated"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
                
tags:
  - name: Auth
    description: Методы для работы с авторизацией и регистрацией.
  - name: User
    description: Методы для работы с профилем пользователя.
  - name: Cart
    description: Методы для работы с корзиной.
