openapi: 3.0.0
info:
  title: Authentication API
  version: 0.0.1
  description: API для регистрации, входа и подтверждения учетных записей пользователей.

servers:
  - url: http://localhost:5000
    description: Local server

paths:
  /api/auth/confirm:
    get:
      tags:
        - Auth
      summary: Подтверждение пользователя
      description: Подтверждает учетную запись пользователя на основе идентификатора.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Уникальный идентификатор пользователя.
      responses:
        '200':
          description: Успешное подтверждение
          content:
            application/json:
              schema:
                type: string
                example: "Confirmation successful"
        '400':
          description: Ошибка подтверждения
          content:
            application/json:
              schema:
                type: string
                example: "Failed to find a user with this id"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
  /api/auth/signup:
    post:
      tags:
        - Auth
      summary: Регистрация нового пользователя
      description: Регистрирует нового пользователя на основе email и пароля.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Электронная почта пользователя.
                password:
                  type: string
                  format: password
                  description: Пароль пользователя.
              required:
                - email
                - password
      responses:
        '200':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Уникальный идентификатор пользователя
                  email:
                    type: string
                    format: email
                    description: Электронная почта пользователя
                  activated:
                    type: integer
                    description: Статус подтверждения пользователя (0 — не активирован, 1 — активирован)
                    example: 0
        '400':
          description: Ошибка при регистрации
          content:
            application/json:
              schema:
                type: string
              examples:
                InvalidInput:
                  summary: Неверные данные
                  value: "Invalid input"
                EmailReserved:
                  summary: Электронная почта уже используется
                  value: "This email already had been reserved"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
  /api/auth/signin:
    post:
      tags:
        - Auth
      summary: Аутентификация пользователя
      description: Аутентифицирует пользователя на основе email и пароля.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Электронная почта пользователя
                password:
                  type: string
                  format: password
                  description: Пароль пользователя
              required:
                - email
                - password
      responses:
        '200':
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                type: string
                example: "Authentication successful"
        '400':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                type: string
              examples:
                InvalidInput:
                  summary: Неверные данные
                  value: "Invalid input"
                UserNotFound:
                  summary: Пользователь не найден
                  value: "Failed to find this user"
                UserNotActivated:
                  summary: Пользователь не активирован
                  value: "This user is not activated"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
  /api/goods/{id}:
    get:
      tags:
        - Goods
      summary: Получение товара по ID
      description: Возвращает информацию о товаре на основе его уникального идентификатора.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Уникальный идентификатор товара.
      responses:
        '200':
          description: Информация о товаре
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Уникальный идентификатор товара
                  name:
                    type: string
                    description: Название товара
                  description:
                    type: string
                    description: Описание товара
                  price:
                    type: number
                    description: Цена товара
                  categoryId:
                    type: string
                    description: Идентификатор категории товара
                  photos:
                    type: array
                    items:
                      type: string
                    description: Массив строк, представляющих имена изображений товара
        '400':
          description: Товар не найден
          content:
            application/json:
              schema:
                type: string
                example: "Goods not found"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
    patch:
      tags:
        - Goods
      summary: Обновление товара по ID
      description: Обновляет данные существующего товара на основе переданного ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Уникальный идентификатор товара.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Название товара
                description:
                  type: string
                  description: Описание товара
                price:
                  type: number
                  description: Цена товара
                categoryId:
                  type: string
                  description: Идентификатор категории, к которой принадлежит товар
                photos:
                  type: array
                  items:
                    type: string
                  description: Массив строк, представляющих имена изображений товара
      responses:
        '200':
          description: Товар успешно обновлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Уникальный идентификатор товара
                  name:
                    type: string
                    description: Название товара
                  description:
                    type: string
                    description: Описание товара
                  price:
                    type: number
                    description: Цена товара
                  categoryId:
                    type: string
                    description: Идентификатор категории товара
                  photos:
                    type: array
                    items:
                      type: string
                    description: Массив строк, представляющих имена изображений товара
        '400':
          description: Ошибка при обновлении товара
          content:
            application/json:
              schema:
                type: string
                example: "Goods not found or invalid input"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
    delete:
      tags:
        - Goods
      summary: Удаление товара по ID
      description: Удаляет товар на основе его уникального идентификатора.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Уникальный идентификатор товара.
      responses:
        '204':
          description: Товар успешно удален
        '400':
          description: Ошибка при удалении товара
          content:
            application/json:
              schema:
                type: string
                example: "Goods not found"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
  /api/goods:
    get:
      tags:
        - Goods
      summary: Получение списка всех товаров
      description: Возвращает список всех товаров.
      responses:
        '200':
          description: Список товаров
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Уникальный идентификатор товара
                    name:
                      type: string
                      description: Название товара
                    description:
                      type: string
                      description: Описание товара
                    price:
                      type: number
                      description: Цена товара
                    categoryId:
                      type: string
                      description: Идентификатор категории товара
                    photos:
                      type: array
                      items:
                        type: string
                      description: Массив строк, представляющих имена изображений товара
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
    post:
      tags:
        - Goods
      summary: Создание нового товара
      description: Создает новый товар на основе переданных данных.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Название товара
                description:
                  type: string
                  description: Описание товара
                price:
                  type: number
                  description: Цена товара
                categoryId:
                  type: string
                  description: Идентификатор категории, к которой принадлежит товар
                photos:
                    type: array
                    items:
                      type: string
                    description: Массив строк, представляющих имена изображений товара
              required:
                - name
                - price
                - categoryId
      responses:
        '201':
          description: Товар успешно создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Уникальный идентификатор товара
                  name:
                    type: string
                    description: Название товара
                  description:
                    type: string
                    description: Описание товара
                  price:
                    type: number
                    description: Цена товара
                  categoryId:
                    type: string
                    description: Идентификатор категории товара
                  photos:
                    type: array
                    items:
                      type: string
                    description: Массив строк, представляющих имена изображений товара
        '400':
          description: Ошибка при создании товара
          content:
            application/json:
              schema:
                type: string
                example: "Invalid input"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: string
                example: "Internal server error"
    

tags:
  - name: Auth
    description: Методы для работы с авторизацией и регистрацией.
  - name: User
    description: Методы для работы с профилем пользователя.
  - name: Cart
    description: Методы для работы с корзиной.
  - name: Goods
    description: Методы для работы с товаром.
